@baseUrl =  https://localhost:5000/PoliceOfficers

### 
# @name CreatePoliceOfficer
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZWFkZXJAcGQuY29tIiwidW5pcXVlX25hbWUiOiJyZWFkZXJAcGQuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoicmVhZGVyQHBkLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlJlYWRlciIsIm5iZiI6MTcxMzAxMjM4MSwiZXhwIjoxNzEzMDQxMTgxLCJpc3MiOiJwZCIsImF1ZCI6InBkLXVzZXJzIn0.gP1yvXyL9t2IMipxRPLsa4RywEwugvV0CgY1wxg3cP8

{
  "FirstName": "Anderson",
  "LastName": "Dupont",
  "BadgeNumber": {
    "Value": "#-944-866-232"
  },
  "BirthDate": {
    "Value": "1965-08-30"
  }
}

### 
# @name GetPoliceOfficers
GET {{baseUrl}}
Authorization: {{token}}

### 
# @name UpdatePoliceOfficer
PUT {{baseUrl}}/08dc564d-10f9-4452-88ce-bba03e31391c
Authorization: {{token}}
Content-Type: application/json

{
  "officer": {
    "FirstName": "Jon-Michael",
    "LastName": "Mantinband",
    "BadgeNumber": {
      "Value": "#-12132323-123-123"
    },
    "BirthDate": {
      "Value": "1990-02-01"
    }
  }
}