// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoliceDepartment.Infrastructure.DAL;

#nullable disable

namespace PoliceDepartment.Infrastructure.Migrations
{
    [DbContext(typeof(PoliceDepartmentDbContext))]
    [Migration("20230415163322_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PoliceDepartment.Core.Entities.PoliceOfficer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BadgeNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PoliceOfficers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0b6cd5c-6547-48f8-bd6c-50d2d48f7ed9"),
                            BadgeNumber = "#-123-436-534",
                            BirthDate = new DateTime(1995, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bobson",
                            LastName = "Dugnutt"
                        },
                        new
                        {
                            Id = new Guid("7d0ee9be-bdd7-462d-8152-0e1f2d887b2c"),
                            BadgeNumber = "#-123-392-166",
                            BirthDate = new DateTime(1985, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sleve",
                            LastName = "McDeichel"
                        },
                        new
                        {
                            Id = new Guid("6f0e19ee-8c7c-4624-af7c-7c6eed8cea05"),
                            BadgeNumber = "#-232-767-666",
                            BirthDate = new DateTime(1965, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Rey",
                            LastName = "McSriff"
                        },
                        new
                        {
                            Id = new Guid("76f47e29-60ed-469c-9336-64623ef5f2f0"),
                            BadgeNumber = "#-896-921-338",
                            BirthDate = new DateTime(1975, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Glenallen",
                            LastName = "Mixon"
                        },
                        new
                        {
                            Id = new Guid("26fe312c-32ae-47f4-a6a1-554ccb68bdd7"),
                            BadgeNumber = "#-766-655-594",
                            BirthDate = new DateTime(1968, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Rawl",
                            LastName = "Chamgerlain"
                        },
                        new
                        {
                            Id = new Guid("48720644-6130-4744-81ed-1528d01cd617"),
                            BadgeNumber = "#-778-988-363",
                            BirthDate = new DateTime(1986, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kevin",
                            LastName = "Nogilny"
                        },
                        new
                        {
                            Id = new Guid("32c75a28-ef4e-4b5f-972a-4a5aa057d985"),
                            BadgeNumber = "#-569-450-729",
                            BirthDate = new DateTime(1982, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Tony",
                            LastName = "Smherik"
                        },
                        new
                        {
                            Id = new Guid("0c51a7c4-e1b1-4c76-8613-e4d052c6ef8b"),
                            BadgeNumber = "#-454-443-541",
                            BirthDate = new DateTime(1973, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Willie",
                            LastName = "Dustice"
                        },
                        new
                        {
                            Id = new Guid("97d09b2b-263c-4f2e-9559-a3332e8e50d8"),
                            BadgeNumber = "#-405-341-807",
                            BirthDate = new DateTime(1995, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mario",
                            LastName = "McRwlain"
                        },
                        new
                        {
                            Id = new Guid("50e4dc59-b8b4-4500-a81c-27f95c64af17"),
                            BadgeNumber = "#-569-541-836",
                            BirthDate = new DateTime(1956, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Todd",
                            LastName = "Bonzalez"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
