### CreatePoliceOfficer
POST https://localhost:5000/PoliceOfficers
Content-Type: application/json

{
  "FirstName": "Amichai",
  "LastName": "Mantinband",
  "BadgeNumber": {
    "Value": "#-123-123-123"
  },
  "BirthDate": {
    "Value": "1990-02-01" 
  }
}

### GetPoliceOfficers
GET https://localhost:5000/PoliceOfficers