### CreatePoliceOfficer
POST https://localhost:5000/PoliceOfficers
Content-Type: application/json

{
  "FirstName": "Amichai",
  "LastName": "Mantinband",
  "BadgeNumber": {
    "Value": "#-123-123-123"
  },
  "BirthDate": {
    "Value": "1990-02-01" 
  }
}

### GetPoliceOfficers
GET https://localhost:5000/PoliceOfficers

### UpdatePoliceOfficer
PUT https://localhost:5000/PoliceOfficers/08dc564d-10f9-4452-88ce-bba03e31391c
Content-Type: application/json

{
  "officer": {
    "FirstName": "Jon-Michael",
    "LastName": "Mantinband",
    "BadgeNumber": {
      "Value": "#-12132323-123-123"
    },
    "BirthDate": {
      "Value": "1990-02-01"
    }
  }
}
