services:
  
  db:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'dev'
    ports:
      - 3306:3306
    volumes:
      - /Users/Bartek/Projects/mysqlDockerVolume:/var/lib/mysql
  
  queue:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
  
  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite:3.19.0-arm64
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002