services:
  
  db:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'dev'
    ports:
      - 3306:3306
    volumes:
      - /mysql:/var/lib/mysql